img_1 = imread('pout.tif');
img_2 = imread('cameraman.tif');
img_1_stretched = contrast_stretching_cinza(img_1, 80, 160, 30, 245);
img_2_stretched = contrast_stretching_cinza(img_2, 100, 200, 30, 250);
figure;
subplot(2,2,1); imshow(img_1); title('Original image');
subplot(2,2,2); imhist(img_1);
subplot(2,2,3); imshow(img_1_stretched); title('Contrast stretching');
subplot(2,2,4); imhist(img_1_stretched);
figure;
subplot(2,2,1); imshow(img_2); title('Original image');
subplot(2,2,2); imhist(img_2);
subplot(2,2,3); imshow(img_2_stretched); title('Contrast stretching');
subplot(2,2,4); imhist(img_2_stretched);